controller:
  adminPassword: "${admin_password}"
  serviceType: LoadBalancer
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"
  installPlugins:
    - kubernetes:4336.v8b_97f0484a_c0
    - workflow-aggregator:600.vb_57cdd26fdd7
    - git:5.7.0
    - configuration-as-code:1932.v75cb_b_f1b_698d
    - pipeline-stage-view:2.34
  JCasC:
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: "Jenkins on EKS - CI/CD Pipeline"

agent:
  enabled: true
  resources:
    requests:
      cpu: "256m"
      memory: "256Mi"
    limits:
      cpu: "512m"
      memory: "512Mi"

persistence:
  enabled: true
  size: "8Gi"
