controller:
  admin:
    password: "${admin_password}"
  serviceType: LoadBalancer
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"
  installPlugins:
    - kubernetes:latest
    - workflow-aggregator:latest
    - git:latest
    - configuration-as-code:latest
    - pipeline-stage-view:latest
  JCasC:
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: "Jenkins on EKS - CI/CD Pipeline"

agent:
  enabled: true
  resources:
    requests:
      cpu: "256m"
      memory: "256Mi"
    limits:
      cpu: "512m"
      memory: "512Mi"

persistence:
  enabled: true
  storageClass: gp2
  size: "8Gi"
