apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: django-app
  namespace: {{ .Release.Namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.application.repoURL }}
    targetRevision: {{ .Values.application.targetRevision }}
    path: {{ .Values.application.path }}
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.application.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
